
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nelso
 */
public class View extends javax.swing.JFrame {
    private JFileChooser fc = new JFileChooser(".");
    File data ;
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpenData = new javax.swing.JPanel();
        buttonOpenData = new javax.swing.JButton();
        pathOpenData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        urlText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panelQuery = new javax.swing.JPanel();
        queryTextArea = new javax.swing.JScrollPane();
        queryText = new javax.swing.JTextArea();
        resultQueryTextArea = new javax.swing.JScrollPane();
        resultQueryText = new javax.swing.JTextArea();
        queryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelOpenData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonOpenData.setText("Ope Datafile");
        buttonOpenData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenDataActionPerformed(evt);
            }
        });

        pathOpenData.setEditable(false);

        jLabel1.setText("Url consulta remota");

        jButton1.setText("Guardar resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpenDataLayout = new javax.swing.GroupLayout(panelOpenData);
        panelOpenData.setLayout(panelOpenDataLayout);
        panelOpenDataLayout.setHorizontalGroup(
            panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenDataLayout.createSequentialGroup()
                .addGroup(panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpenDataLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(buttonOpenData))
                        .addGap(51, 51, 51)
                        .addGroup(panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pathOpenData)
                            .addComponent(urlText, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
                    .addGroup(panelOpenDataLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpenDataLayout.setVerticalGroup(
            panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenDataLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOpenData)
                    .addComponent(pathOpenData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelOpenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(urlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        queryText.setColumns(20);
        queryText.setRows(5);
        queryTextArea.setViewportView(queryText);

        resultQueryText.setEditable(false);
        resultQueryText.setColumns(20);
        resultQueryText.setRows(5);
        resultQueryTextArea.setViewportView(resultQueryText);

        queryButton.setText("Ejecutar consulta");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQueryLayout = new javax.swing.GroupLayout(panelQuery);
        panelQuery.setLayout(panelQueryLayout);
        panelQueryLayout.setHorizontalGroup(
            panelQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueryLayout.createSequentialGroup()
                .addComponent(queryTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(queryButton)
                .addGap(22, 22, 22)
                .addComponent(resultQueryTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQueryLayout.setVerticalGroup(
            panelQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueryLayout.createSequentialGroup()
                .addGroup(panelQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultQueryTextArea)
                    .addGroup(panelQueryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(queryTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelQueryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(queryButton)
                .addGap(207, 207, 207))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOpenData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOpenData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpenDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenDataActionPerformed
        int res = fc.showOpenDialog(null);
        
        if (res == JFileChooser.APPROVE_OPTION) {
            try {
                File file;
                file = new File(fc.getSelectedFile().getCanonicalPath());
                if(!file.exists()){
                     JOptionPane.showMessageDialog(this,  "Fichero no encontrado", "Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    this.data=file;
                    pathOpenData.setText(this.data.getAbsolutePath());
                }
                
            } catch (IOException ex) {
                Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }     
    }//GEN-LAST:event_buttonOpenDataActionPerformed

    private void queryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionPerformed
        if(urlText.getText().isEmpty()){
            if( this.data == null || !this.data.exists()){
                JOptionPane.showMessageDialog(this,  "Habra un fichero de datos", "Error",JOptionPane.ERROR_MESSAGE);
                return;
             
            }
            String result = Consultor.consultar(this.data.getAbsolutePath(), queryText.getText());
            resultQueryText.setText(result);
        }else{
             String result = Consultor.consultaRemota(urlText.getText(), queryText.getText());
             resultQueryText.setText(result);
        }
        
        
    }//GEN-LAST:event_queryButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Consultor.current == null){
             JOptionPane.showMessageDialog(this,  "Haga una consulta", "Error",JOptionPane.ERROR_MESSAGE);
             return;
        }
        int res = fc.showSaveDialog(null);
            if (res == JFileChooser.APPROVE_OPTION) {
                try {
                    String path = fc.getSelectedFile().getCanonicalPath();
                    if(!Consultor.saveResult(path))JOptionPane.showMessageDialog(this,  "Error al guardar", "Error",JOptionPane.ERROR_MESSAGE);
                    
                    
                    
                } catch (IOException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                return;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOpenData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelOpenData;
    private javax.swing.JPanel panelQuery;
    private javax.swing.JTextField pathOpenData;
    private javax.swing.JButton queryButton;
    private javax.swing.JTextArea queryText;
    private javax.swing.JScrollPane queryTextArea;
    private javax.swing.JTextArea resultQueryText;
    private javax.swing.JScrollPane resultQueryTextArea;
    private javax.swing.JTextField urlText;
    // End of variables declaration//GEN-END:variables
}
